language: php
dist: trusty
php:
  - "7.1"
  - "7.0"
  - "5.6"
  - "5.5"
  - "5.4"
install:
  - sudo apt-get update
  - sudo apt-get install pdftk
  - composer self-update
  - composer install
  - composer require --prefer-dist mikehaertl/pdftk2-precise-amd64
  - sudo cp vendor/bin/pdftk /usr/bin/
